
all:
	pdflatex 3d_tet4_taylor_green_0p2
	bibtex 3d_tet4_taylor_green_0p2
	pdflatex 3d_tet4_taylor_green_0p2
	bibtex 3d_tet4_taylor_green_0p2
	pdflatex 3d_tet4_taylor_green_0p2

clean:
	-rm -f *.aux *.log *.dvi *.bbl *.blg *~
