# CMake Testfile

# nightly tests
add_test(dgNonConformalThreeBlade "[" "-f" "${NIGHTLY_TEST_RESULT_DIRECTORY}/dgNonConformalThreeBlade/PASS" "]")
add_test(quad9HC "[" "-f" "${NIGHTLY_TEST_RESULT_DIRECTORY}/quad9HC/PASS" "]")
add_test(milestoneRun "[" "-f" "${NIGHTLY_TEST_RESULT_DIRECTORY}/milestoneRun/PASS" "]")
add_test(fluidsPmrChtPeriodic "[" "-f" "${NIGHTLY_TEST_RESULT_DIRECTORY}/fluidsPmrChtPeriodic/PASS" "]")
add_test(heatedBackStep "[" "-f" "${NIGHTLY_TEST_RESULT_DIRECTORY}/heatedBackStep/PASS" "]")
add_test(actuatorLine "[" "-f" "${NIGHTLY_TEST_RESULT_DIRECTORY}/actuatorLine/PASS" "]")
add_test(nonIsoElemOpenJet "[" "-f" "${NIGHTLY_TEST_RESULT_DIRECTORY}/nonIsoElemOpenJet/PASS" "]")
add_test(ablUnstableEdge "[" "-f" "${NIGHTLY_TEST_RESULT_DIRECTORY}/ablUnstableEdge/PASS" "]")
add_test(edgeContact3D "[" "-f" "${NIGHTLY_TEST_RESULT_DIRECTORY}/edgeContact3D/PASS" "]")
add_test(dgNonConformal3dFluidsHexTet "[" "-f" "${NIGHTLY_TEST_RESULT_DIRECTORY}/dgNonConformal3dFluidsHexTet/PASS" "]")
add_test(nonIsoNonUniformElemOpenJet "[" "-f" "${NIGHTLY_TEST_RESULT_DIRECTORY}/nonIsoNonUniformElemOpenJet/PASS" "]")
add_test(dgNonConformalEdgeCylinder "[" "-f" "${NIGHTLY_TEST_RESULT_DIRECTORY}/dgNonConformalEdgeCylinder/PASS" "]")
add_test(inputFireElem "[" "-f" "${NIGHTLY_TEST_RESULT_DIRECTORY}/inputFireElem/PASS" "]")
add_test(dgNonConformal3dFluids "[" "-f" "${NIGHTLY_TEST_RESULT_DIRECTORY}/dgNonConformal3dFluids/PASS" "]")
add_test(edgePipeCHT "[" "-f" "${NIGHTLY_TEST_RESULT_DIRECTORY}/edgePipeCHT/PASS" "]")
add_test(dgNonConformal "[" "-f" "${NIGHTLY_TEST_RESULT_DIRECTORY}/dgNonConformal/PASS" "]")
add_test(nonIsoEdgeOpenJet "[" "-f" "${NIGHTLY_TEST_RESULT_DIRECTORY}/nonIsoEdgeOpenJet/PASS" "]")
add_test(nonIsoNonUniformEdgeOpenJet "[" "-f" "${NIGHTLY_TEST_RESULT_DIRECTORY}/nonIsoNonUniformEdgeOpenJet/PASS" "]")
add_test(hoVortex "[" "-f" "${NIGHTLY_TEST_RESULT_DIRECTORY}/hoVortex/PASS" "]")
add_test(elemBackStepLRSST "[" "-f" "${NIGHTLY_TEST_RESULT_DIRECTORY}/elemBackStepLRSST/PASS" "]")
add_test(dgNonConformalFluidsEdge "[" "-f" "${NIGHTLY_TEST_RESULT_DIRECTORY}/dgNonConformalFluidsEdge/PASS" "]")
add_test(concentricRad "[" "-f" "${NIGHTLY_TEST_RESULT_DIRECTORY}/concentricRad/PASS" "]")
add_test(ablStableElem "[" "-f" "${NIGHTLY_TEST_RESULT_DIRECTORY}/ablStableElem/PASS" "]")
add_test(femHC "[" "-f" "${NIGHTLY_TEST_RESULT_DIRECTORY}/femHC/PASS_NP1" "]")
add_test(hoHelium "[" "-f" "${NIGHTLY_TEST_RESULT_DIRECTORY}/hoHelium/PASS" "]")
add_test(mixedTetPipe "[" "-f" "${NIGHTLY_TEST_RESULT_DIRECTORY}/mixedTetPipe/PASS" "]")
add_test(dgNonConformalEdge "[" "-f" "${NIGHTLY_TEST_RESULT_DIRECTORY}/dgNonConformalEdge/PASS" "]")
add_test(movingCylinder "[" "-f" "${NIGHTLY_TEST_RESULT_DIRECTORY}/movingCylinder/PASS" "]")
add_test(oversetFluidsEdge "[" "-f" "${NIGHTLY_TEST_RESULT_DIRECTORY}/oversetFluidsEdge/PASS" "]")
add_test(elemClosedDomain "[" "-f" "${NIGHTLY_TEST_RESULT_DIRECTORY}/elemClosedDomain/PASS" "]")
add_test(variableDensMMS "[" "-f" "${NIGHTLY_TEST_RESULT_DIRECTORY}/variableDensMMS/PASS" "]")
add_test(inputFireEdgeUpwind "[" "-f" "${NIGHTLY_TEST_RESULT_DIRECTORY}/inputFireEdgeUpwind/PASS" "]")
add_test(heatedWaterChannel "[" "-f" "${NIGHTLY_TEST_RESULT_DIRECTORY}/heatedWaterChannel/PASS" "]")
add_test(edgeHybridFluids "[" "-f" "${NIGHTLY_TEST_RESULT_DIRECTORY}/edgeHybridFluids/PASS" "]")
add_test(elemPipeCHT "[" "-f" "${NIGHTLY_TEST_RESULT_DIRECTORY}/elemPipeCHT/PASS" "]")
add_test(elemHybridFluids "[" "-f" "${NIGHTLY_TEST_RESULT_DIRECTORY}/elemHybridFluids/PASS" "]")
add_test(periodic3dElem "[" "-f" "${NIGHTLY_TEST_RESULT_DIRECTORY}/periodic3dElem/PASS_NP1" "]")
add_test(periodic3dElem "[" "-f" "${NIGHTLY_TEST_RESULT_DIRECTORY}/periodic3dElem/PASS_NP4" "]")
add_test(periodic3dElem "[" "-f" "${NIGHTLY_TEST_RESULT_DIRECTORY}/periodic3dElem/PASS_NP8" "]")
add_test(unitTests "[" "-f" "${NIGHTLY_TEST_RESULT_DIRECTORY}/unitTests/unit_test_output.np1" "]")
add_test(unitTests "[" "-f" "${NIGHTLY_TEST_RESULT_DIRECTORY}/unitTests/unit_test_output.np2" "]")
add_test(periodic3dEdge "[" "-f" "${NIGHTLY_TEST_RESULT_DIRECTORY}/periodic3dEdge/PASS_NP1" "]")
add_test(periodic3dEdge "[" "-f" "${NIGHTLY_TEST_RESULT_DIRECTORY}/periodic3dEdge/PASS_NP4" "]")
add_test(periodic3dEdge "[" "-f" "${NIGHTLY_TEST_RESULT_DIRECTORY}/periodic3dEdge/PASS_NP8" "]")
add_test(heliumPlume "[" "-f" "${NIGHTLY_TEST_RESULT_DIRECTORY}/heliumPlume/PASS" "]")
#add_test(hdf5VarZChi "[" "-f" "${NIGHTLY_TEST_RESULT_DIRECTORY}/hdf5VarZChi/PASS" "]")
add_test(dgNonConformal3dFluidsP1P2 "[" "-f" "${NIGHTLY_TEST_RESULT_DIRECTORY}/dgNonConformal3dFluidsP1P2/PASS" "]")
add_test(elemHybridFluidsShift "[" "-f" "${NIGHTLY_TEST_RESULT_DIRECTORY}/elemHybridFluidsShift/PASS" "]")
add_test(steadyTaylorVortex "[" "-f" "${NIGHTLY_TEST_RESULT_DIRECTORY}/steadyTaylorVortex/PASS" "]")
add_test(overset "[" "-f" "${NIGHTLY_TEST_RESULT_DIRECTORY}/overset/PASS" "]")
add_test(oversetFluids "[" "-f" "${NIGHTLY_TEST_RESULT_DIRECTORY}/oversetFluids/PASS" "]")
add_test(dgNonConformalFluids "[" "-f" "${NIGHTLY_TEST_RESULT_DIRECTORY}/dgNonConformalFluids/PASS" "]")
add_test(ductWedge "[" "-f" "${NIGHTLY_TEST_RESULT_DIRECTORY}/ductWedge/PASS" "]")


# Performance tests
add_test(oversetFluids "[" "-f" "${PERF_TEST_RESULT_DIRECTORY}/oversetHybrid/PASS" "]")
add_test(dgNonConformalFluids "[" "-f" "${PERF_TEST_RESULT_DIRECTORY}/uqSlidingMesh/PASS" "]")
add_test(ductWedge "[" "-f" "${PERF_TEST_RESULT_DIRECTORY}/uqSlidingMeshDG/PASS" "]")
add_test(ductWedge "[" "-f" "${PERF_TEST_RESULT_DIRECTORY}/waleElemXflowMixFrac3.5m/PASS" "]")
